In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np

In [2]:
from tensorflow import keras

In [20]:
IMAGE_SIZE = 256
BATCH_SIZE = 32
CHANNELS = 3
EPOCHS = 50
batch_size = 32

In [35]:
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    "PlantVillage",
    shuffle = True,
    image_size = (IMAGE_SIZE, IMAGE_SIZE),
    batch_size = BATCH_SIZE
)

#dataset = keras.preprocessing.image_dataset_from_directory(
#    directory="celeb_dataset", label_mode=None, image_size=(64, 64), batch_size=32,
#    shuffle=True, seed=None, validation_split=None,
#).map(lambda x: x / 255.0)

Found 2152 files belonging to 3 classes.


In [37]:
class_names = dataset.class_names
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [38]:
from tensorflow.keras import layers

normalization_layer = tf.keras.layers.experimental.preprocessing.Rescaling(1./255)

dataset = dataset.map(lambda x, y: (normalization_layer(x), y))

In [53]:
for idx, (real) in enumerate(tqdm(dataset)):
    #print(idx)
    print(real[0])

  6%|▌         | 4/68 [00:00<00:03, 16.15it/s]

tf.Tensor(
[[[[0.59607846 0.5882353  0.5921569 ]
   [0.61960787 0.6117647  0.6156863 ]
   [0.62352943 0.6156863  0.627451  ]
   ...
   [0.5254902  0.49803925 0.5294118 ]
   [0.52156866 0.49411768 0.5254902 ]
   [0.5254902  0.49803925 0.5294118 ]]

  [[0.59607846 0.5882353  0.5921569 ]
   [0.6156863  0.60784316 0.6117647 ]
   [0.61960787 0.6117647  0.62352943]
   ...
   [0.52156866 0.49411768 0.5254902 ]
   [0.5254902  0.49803925 0.5294118 ]
   [0.53333336 0.5058824  0.5372549 ]]

  [[0.59607846 0.5882353  0.6       ]
   [0.6117647  0.6039216  0.6156863 ]
   [0.6156863  0.60784316 0.61960787]
   ...
   [0.5254902  0.49803925 0.5294118 ]
   [0.5294118  0.5019608  0.53333336]
   [0.5372549  0.50980395 0.5411765 ]]

  ...

  [[0.5803922  0.5411765  0.53333336]
   [0.6        0.56078434 0.5529412 ]
   [0.6117647  0.57254905 0.5647059 ]
   ...
   [0.56078434 0.5294118  0.52156866]
   [0.5529412  0.52156866 0.5137255 ]
   [0.5137255  0.48235297 0.47450984]]

  [[0.58431375 0.54509807 0.537254

 19%|█▉        | 13/68 [00:00<00:01, 31.74it/s]

tf.Tensor(
[[[[0.72156864 0.70980394 0.7372549 ]
   [0.6431373  0.6313726  0.65882355]
   [0.6392157  0.627451   0.654902  ]
   ...
   [0.7607844  0.75294125 0.7960785 ]
   [0.7607844  0.75294125 0.7960785 ]
   [0.75294125 0.74509805 0.78823537]]

  [[0.5803922  0.5686275  0.59607846]
   [0.6156863  0.6039216  0.6313726 ]
   [0.6666667  0.654902   0.68235296]
   ...
   [0.77647066 0.7686275  0.8117648 ]
   [0.7725491  0.76470596 0.8078432 ]
   [0.7686275  0.7607844  0.80392164]]

  [[0.7058824  0.69411767 0.72156864]
   [0.7843138  0.7725491  0.8000001 ]
   [0.7607844  0.7490196  0.77647066]
   ...
   [0.77647066 0.7686275  0.8117648 ]
   [0.77647066 0.7686275  0.8117648 ]
   [0.7725491  0.76470596 0.8078432 ]]

  ...

  [[0.58431375 0.59607846 0.6313726 ]
   [0.627451   0.6392157  0.6745098 ]
   [0.5411765  0.5529412  0.5882353 ]
   ...
   [0.7019608  0.69411767 0.7490196 ]
   [0.6745098  0.6666667  0.72156864]
   [0.67058825 0.6627451  0.7176471 ]]

  [[0.58431375 0.59607846 0.631372

 32%|███▏      | 22/68 [00:00<00:01, 32.92it/s]

tf.Tensor(
[[[[0.70980394 0.7176471  0.76470596]
   [0.7372549  0.74509805 0.79215693]
   [0.75294125 0.7607844  0.8078432 ]
   ...
   [0.61960787 0.62352943 0.69411767]
   [0.5372549  0.5411765  0.6117647 ]
   [0.50980395 0.5137255  0.58431375]]

  [[0.7490196  0.7568628  0.80392164]
   [0.79215693 0.8000001  0.8470589 ]
   [0.81568635 0.8235295  0.8705883 ]
   ...
   [0.60784316 0.6117647  0.68235296]
   [0.5529412  0.5568628  0.627451  ]
   [0.56078434 0.5647059  0.63529414]]

  [[0.7019608  0.70980394 0.7568628 ]
   [0.7294118  0.7372549  0.7843138 ]
   [0.7411765  0.7490196  0.7960785 ]
   ...
   [0.59607846 0.6        0.67058825]
   [0.5529412  0.5568628  0.627451  ]
   [0.57254905 0.5764706  0.64705884]]

  ...

  [[0.63529414 0.627451   0.6784314 ]
   [0.63529414 0.627451   0.6784314 ]
   [0.63529414 0.627451   0.6784314 ]
   ...
   [0.43529415 0.42352945 0.4666667 ]
   [0.53333336 0.52156866 0.5647059 ]
   [0.5019608  0.4901961  0.53333336]]

  [[0.6392157  0.6313726  0.682352

 44%|████▍     | 30/68 [00:01<00:01, 31.36it/s]

tf.Tensor(
[[[[0.34509805 0.30588236 0.34901962]
   [0.37254903 0.33333334 0.37647063]
   [0.38431376 0.34509805 0.38823533]
   ...
   [0.5529412  0.5294118  0.5764706 ]
   [0.5568628  0.53333336 0.5803922 ]
   [0.54901963 0.5254902  0.57254905]]

  [[0.37647063 0.3372549  0.3803922 ]
   [0.38431376 0.34509805 0.38823533]
   [0.3803922  0.34117648 0.38431376]
   ...
   [0.5372549  0.5137255  0.56078434]
   [0.53333336 0.50980395 0.5568628 ]
   [0.5294118  0.5058824  0.5529412 ]]

  [[0.4039216  0.3647059  0.40784317]
   [0.39607847 0.35686275 0.40000004]
   [0.37254903 0.33333334 0.37647063]
   ...
   [0.5294118  0.5058824  0.5529412 ]
   [0.5294118  0.5058824  0.5529412 ]
   [0.5294118  0.5058824  0.5529412 ]]

  ...

  [[0.32941177 0.30588236 0.36078432]
   [0.34509805 0.32156864 0.37647063]
   [0.3647059  0.34117648 0.39607847]
   ...
   [0.5764706  0.56078434 0.61960787]
   [0.5803922  0.5647059  0.62352943]
   [0.5764706  0.56078434 0.61960787]]

  [[0.31764707 0.29411766 0.349019

 50%|█████     | 34/68 [00:01<00:01, 29.72it/s]


tf.Tensor(
[[[[0.78823537 0.7686275  0.79215693]
   [0.7803922  0.7607844  0.7843138 ]
   [0.77647066 0.7568628  0.7803922 ]
   ...
   [0.654902   0.64705884 0.6901961 ]
   [0.67058825 0.6627451  0.7058824 ]
   [0.7019608  0.69411767 0.7372549 ]]

  [[0.8000001  0.7803922  0.80392164]
   [0.79215693 0.7725491  0.7960785 ]
   [0.7803922  0.7607844  0.7843138 ]
   ...
   [0.65882355 0.6509804  0.69411767]
   [0.6745098  0.6666667  0.70980394]
   [0.7058824  0.69803923 0.7411765 ]]

  [[0.79215693 0.7725491  0.7960785 ]
   [0.7843138  0.76470596 0.78823537]
   [0.7803922  0.7607844  0.7843138 ]
   ...
   [0.6666667  0.65882355 0.7019608 ]
   [0.68235296 0.6745098  0.7176471 ]
   [0.70980394 0.7019608  0.74509805]]

  ...

  [[0.7725491  0.7686275  0.78823537]
   [0.7607844  0.7568628  0.77647066]
   [0.77647066 0.7725491  0.79215693]
   ...
   [0.5058824  0.48235297 0.5294118 ]
   [0.56078434 0.5372549  0.5921569 ]
   [0.46274513 0.43921572 0.49411768]]

  [[0.80392164 0.8000001  0.81960

 62%|██████▏   | 42/68 [00:01<00:00, 30.49it/s]

tf.Tensor(
[[[[0.87843144 0.86666673 0.8941177 ]
   [0.7058824  0.69411767 0.72156864]
   [0.65882355 0.64705884 0.6745098 ]
   ...
   [0.5176471  0.4901961  0.5176471 ]
   [0.52156866 0.49411768 0.52156866]
   [0.5686275  0.5411765  0.5686275 ]]

  [[0.65882355 0.64705884 0.6745098 ]
   [0.76470596 0.75294125 0.7803922 ]
   [0.7019608  0.6901961  0.7176471 ]
   ...
   [0.50980395 0.48235297 0.50980395]
   [0.5137255  0.48627454 0.5137255 ]
   [0.5529412  0.5254902  0.5529412 ]]

  [[0.69803923 0.6862745  0.7137255 ]
   [0.82745105 0.81568635 0.8431373 ]
   [0.7607844  0.7490196  0.77647066]
   ...
   [0.5254902  0.49803925 0.5254902 ]
   [0.52156866 0.49411768 0.52156866]
   [0.5568628  0.5294118  0.5568628 ]]

  ...

  [[0.70980394 0.6784314  0.67058825]
   [0.68235296 0.6509804  0.6431373 ]
   [0.6509804  0.61960787 0.6117647 ]
   ...
   [0.4901961  0.4431373  0.4431373 ]
   [0.47450984 0.427451   0.427451  ]
   [0.4431373  0.39607847 0.39607847]]

  [[0.69411767 0.6627451  0.654902

 74%|███████▎  | 50/68 [00:01<00:00, 31.90it/s]

tf.Tensor(
[[[[0.4431373  0.43137258 0.47450984]
   [0.41960788 0.40784317 0.45098042]
   [0.56078434 0.54901963 0.5921569 ]
   ...
   [0.49411768 0.48627454 0.5294118 ]
   [0.52156866 0.5137255  0.5568628 ]
   [0.54509807 0.5372549  0.5803922 ]]

  [[0.5176471  0.5058824  0.54901963]
   [0.627451   0.6156863  0.65882355]
   [0.454902   0.4431373  0.48627454]
   ...
   [0.42352945 0.4156863  0.45882356]
   [0.45882356 0.45098042 0.49411768]
   [0.4901961  0.48235297 0.5254902 ]]

  [[0.5686275  0.5568628  0.6       ]
   [0.44705886 0.43529415 0.4784314 ]
   [0.50980395 0.49803925 0.5411765 ]
   ...
   [0.47058827 0.46274513 0.5058824 ]
   [0.47450984 0.4666667  0.50980395]
   [0.4784314  0.47058827 0.5137255 ]]

  ...

  [[0.69411767 0.68235296 0.70980394]
   [0.7019608  0.6901961  0.7176471 ]
   [0.69803923 0.6862745  0.7137255 ]
   ...
   [0.50980395 0.4901961  0.5176471 ]
   [0.56078434 0.5411765  0.5686275 ]
   [0.6392157  0.61960787 0.64705884]]

  [[0.70980394 0.69803923 0.725490

 90%|████████▉ | 61/68 [00:01<00:00, 42.04it/s]

tf.Tensor(
[[[[0.8117648  0.82745105 0.8745099 ]
   [0.81568635 0.8313726  0.87843144]
   [0.854902   0.8705883  0.9176471 ]
   ...
   [0.6156863  0.63529414 0.72156864]
   [0.5882353  0.60784316 0.69411767]
   [0.627451   0.64705884 0.73333335]]

  [[0.7843138  0.8000001  0.8470589 ]
   [0.7843138  0.8000001  0.8470589 ]
   [0.81568635 0.8313726  0.87843144]
   ...
   [0.6039216  0.62352943 0.70980394]
   [0.5764706  0.59607846 0.68235296]
   [0.59607846 0.6156863  0.7019608 ]]

  [[0.7960785  0.8117648  0.8588236 ]
   [0.78823537 0.80392164 0.85098046]
   [0.8000001  0.81568635 0.86274517]
   ...
   [0.6156863  0.63529414 0.72156864]
   [0.59607846 0.6156863  0.7019608 ]
   [0.5921569  0.6117647  0.69803923]]

  ...

  [[0.5568628  0.5647059  0.6156863 ]
   [0.48627454 0.49411768 0.54509807]
   [0.5764706  0.58431375 0.63529414]
   ...
   [0.43921572 0.4431373  0.52156866]
   [0.3254902  0.32941177 0.40784317]
   [0.38431376 0.38823533 0.4666667 ]]

  [[0.5019608  0.50980395 0.560784

100%|██████████| 68/68 [00:01<00:00, 34.77it/s]

tf.Tensor(
[[[[0.23137257 0.2392157  0.2901961 ]
   [0.2509804  0.25882354 0.30980393]
   [0.25882354 0.26666668 0.31764707]
   ...
   [0.5647059  0.5176471  0.5568628 ]
   [0.54509807 0.49803925 0.5372549 ]
   [0.5254902  0.4784314  0.5176471 ]]

  [[0.2392157  0.24705884 0.29803923]
   [0.24313727 0.2509804  0.3019608 ]
   [0.2392157  0.24705884 0.29803923]
   ...
   [0.5803922  0.53333336 0.57254905]
   [0.5686275  0.52156866 0.56078434]
   [0.5529412  0.5058824  0.54509807]]

  [[0.24705884 0.25490198 0.30588236]
   [0.2392157  0.24705884 0.29803923]
   [0.22352943 0.23137257 0.28235295]
   ...
   [0.5686275  0.52156866 0.56078434]
   [0.5647059  0.5176471  0.5568628 ]
   [0.56078434 0.5137255  0.5529412 ]]

  ...

  [[0.5686275  0.5372549  0.5803922 ]
   [0.54901963 0.5176471  0.56078434]
   [0.5254902  0.49411768 0.5372549 ]
   ...
   [0.5529412  0.5137255  0.54901963]
   [0.57254905 0.53333336 0.5686275 ]
   [0.58431375 0.54509807 0.5803922 ]]

  [[0.53333336 0.5019608  0.545098

In [39]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)

discriminator = keras.Sequential(
    [
        keras.Input(shape=(256, 256, 3)),
        layers.Conv2D(64, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2D(128, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(0.2),
        layers.Conv2D(128, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(0.2),
        layers.Flatten(),
        layers.Dropout(0.2),
        layers.Dense(1, activation="sigmoid"),
    ],
    name="discriminator",
)

In [40]:
discriminator.summary()

Model: "discriminator"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 128, 128, 64)      3136      
                                                                 
 leaky_re_lu_16 (LeakyReLU)  (None, 128, 128, 64)      0         
                                                                 
 conv2d_13 (Conv2D)          (None, 64, 64, 128)       131200    
                                                                 
 leaky_re_lu_17 (LeakyReLU)  (None, 64, 64, 128)       0         
                                                                 
 conv2d_14 (Conv2D)          (None, 32, 32, 128)       262272    
                                                                 
 leaky_re_lu_18 (LeakyReLU)  (None, 32, 32, 128)       0         
                                                                 
 flatten_3 (Flatten)         (None, 131072)          

In [41]:
latent_dim = 128
generator = keras.Sequential(
    [
        keras.Input(shape=(latent_dim,)),
        layers.Dense(8 * 8 * 128),
        layers.Reshape((8, 8, 128)),
        layers.Conv2DTranspose(128, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2DTranspose(256, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2DTranspose(512, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2DTranspose(512, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2DTranspose(512, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2D(3, kernel_size=5, padding="same", activation="sigmoid"),
    ],
    name="generator",
)
generator.summary()

Model: "generator"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 8192)              1056768   
                                                                 
 reshape_1 (Reshape)         (None, 8, 8, 128)         0         
                                                                 
 conv2d_transpose_5 (Conv2DT  (None, 16, 16, 128)      262272    
 ranspose)                                                       
                                                                 
 leaky_re_lu_19 (LeakyReLU)  (None, 16, 16, 128)       0         
                                                                 
 conv2d_transpose_6 (Conv2DT  (None, 32, 32, 256)      524544    
 ranspose)                                                       
                                                                 
 leaky_re_lu_20 (LeakyReLU)  (None, 32, 32, 256)       0 

In [54]:
opt_gen = keras.optimizers.Adam(1e-4)
opt_disc = keras.optimizers.Adam(1e-4)
loss_fn = keras.losses.BinaryCrossentropy()

for epoch in range(1000):
    for idx, (real) in enumerate(tqdm(dataset)):
        batch_size = BATCH_SIZE
        with tf.GradientTape() as gen_tape:
            random_latent_vectors = tf.random.normal(shape = (batch_size, latent_dim))
            fake = generator(random_latent_vectors)

        if idx % 100 == 0:
            img = keras.preprocessing.image.array_to_img(fake[0])
            img.save("generated_data/all_data/generated_img_%03d_%d.png" % (epoch, idx))

        ### Train Discriminator: max log(D(x)) + log(1 - D(G(z)))
        with tf.GradientTape() as disc_tape:
            loss_disc_real = loss_fn(tf.ones((batch_size, 1)), discriminator(real[0]))
            loss_disc_fake = loss_fn(tf.zeros((batch_size, 1)), discriminator(fake))
            loss_disc = (loss_disc_real + loss_disc_fake)/2

        grads = disc_tape.gradient(loss_disc, discriminator.trainable_weights)
        opt_disc.apply_gradients(
            zip(grads, discriminator.trainable_weights)
        )

        ### Train Generator: min log(1 - D(G(z))) <-> max log(D(G(z))
        with tf.GradientTape() as gen_tape:
            fake = generator(random_latent_vectors)
            output = discriminator(fake)
            loss_gen = loss_fn(tf.ones(batch_size, 1), output)

        grads = gen_tape.gradient(loss_gen, generator.trainable_weights)
        opt_gen.apply_gradients(zip(grads, generator.trainable_weights))

  0%|          | 0/68 [04:17<?, ?it/s]


KeyboardInterrupt: 